### ISSUE TITLE
create custom keyboard not working

### ISSUE THREAD

**Issue by hajimAIM** [SakoDroid/telego#17]
I got an error when trying to create a custom keyboard

the error : -

**Unable to send sendMessage. received status code 400
Error code : 400, Description : Bad Request: can't parse keyboard button: Field "request_user" must be of type Object**

my code :- 

package main

import (
	"fmt"

	bt "github.com/SakoDroid/telego/v2"
	cfg "github.com/SakoDroid/telego/v2/configs"
	objs "github.com/SakoDroid/telego/v2/objects"
)

func main() {

	bot, err := bt.NewBot(cfg.Default("your api key"))

	if err != nil {
		panic(err)
	}

	// The general update channel.
	updateChannel := *(bot.GetUpdateChannel())

	// Adding a handler. Everytime the bot receives message "hi" in a private chat, it will respond "hi to you too".
	bot.AddHandler("hi", func(u *objs.Update) {
		_, err := bot.SendMessage(u.Message.Chat.Id, "hi to you too", "", u.Message.MessageId, false, false)
		if err != nil {
			fmt.Println(err)
		}
	}, "private")

	// Adding a handler. Everytime the bot receives bloater message in a private chat, it will respond "default".
	bot.AddHandler("", func(u *objs.Update) {

		//Create the custom keyboard.
		kb := bot.CreateKeyboard(false, false, false, false, "menu")

		//Add buttons to it. First argument is the button's text and the second one is the row number that the button will be added to it.
		kb.AddButton("button1", 1)
		kb.AddButton("button2", 1)
		kb.AddButton("button3", 2)

		//Sends the message along with the keyboard.
		_, err := bot.AdvancedMode().ASendMessage(u.Message.Chat.Id, "invalid keywords, please select to continue", "", u.Message.MessageId, 0, false, false, nil, false, false, kb)
		if err != nil {
			fmt.Println(err)
		}

	}, "private")

	// Monitores any other update. (Updates that don't contain text message "hi" in a private chat)
	go func() {
		for {
			update := <-updateChannel
			fmt.Println(update.Update_id)

			//Some processing on the update
		}
	}()

	bot.Run(true)
}

**Comment by SakoDroid** [comment]
This issue has  been fixed in v2.1.0.

**Comment by hajimAIM** [comment]
tq!
