### ISSUE TITLE
How do I Add event handlers not based on update.Message.Text?

### ISSUE THREAD

**Issue by fulviodenza** [SakoDroid/telego#19]
I discovered that if you send an image in the chat, it will put the text in the Caption, that means that the bot will not react to that. 
It would be useful to have something like this, if needed I can work on an eventual PR if we decide to move forward with this.

**Comment by SakoDroid** [comment]
Hello @fulviodenza 
Thanks for your interest in telego. I like your proposal and i would support and welcome a PR if you are up for it too!

**Comment by fulviodenza** [comment]
Hi, I created a pull requested tested with my bot implementing the feature: https://github.com/SakoDroid/telego/pull/20

**Comment by SakoDroid** [comment]
Thanks for your contribution. Let me run some tests on this feature. I'll merge it after the test.

**Comment by SakoDroid** [comment]
PR#20 has been merged successfully. This feature will be included in the next release (probably v2.2).
