### ISSUE TITLE
Issues with running the bot

### ISSUE THREAD

**Issue by ObiajuluM** [SakoDroid/telego#2]
The bot only runs once and stops, after I call the `bot.Run()` method. should I enclose the method in a while loop
<img width="651" alt="image" src="https://user-images.githubusercontent.com/47371105/161815750-393c0914-cc48-426f-821a-8b84be5ec05d.png">

my_code
```
func start() {
	bot.AddHandler("/start", func(u *objs.Update) {
		// Sends the message to the chat that the message has been received from.
		// The message will be a reply to the received message.
		_, err := bot.SendMessage(u.Message.Chat.Id, "hi i'm a telegram bot", "", u.Message.MessageId, false, false)
		if err != nil {
			log.Fatal(err)
		}
	}, "private", "group") // this handler will only work if the received message is from a private chat or a group chat.
}

func main() {

	// update configs
	up := cfg.DefaultUpdateConfigs()

	// Bot configs
	cf := cfg.BotConfigs{
		BotAPI:         cfg.DefaultBotAPI,  //This is the address of the bot API server. If you are not running a local api server, use cfg.DefaultBotApi constant for this field.
		APIKey:         token,              // bot father api key
		UpdateConfigs:  up,                 // This is the update related configs such as update frequency (default : 300 milliseconds). You can use cfg.DefaultUpdateConfigs() method for this field
		Webhook:        false,              // Pass true if you want to use webhook for receiving updates. (Telego currently does not support webhook).
		LogFileAddress: cfg.DefaultLogFile, // the logs of the bot
	}

	bot, err = bt.NewBot(&cf)

	if err == nil {
		//Start the bot.
		err = bot.Run()
		if err == nil {
			start()
		} else {
			fmt.Println(err)
		}
	} else {
		fmt.Println(err)
	}
}
```

**Comment by SakoDroid** [comment]
Thank you for submiting your issue!
What do you mean it stops? Your program exists or it dose not receive any updates? Please share some more information so that i can help you better, thanks!

**Comment by SakoDroid** [comment]
The problem is you dont wait for anythig, you just start the bot (which works async) and then you add a handler and thats all. As you may already know when the go main routine finishes (main function) the program exists and that is exactly whats is happeing in your code. Try creating a channel and wait for a value from ghe channel or just register a global channel to bot. I will try to show the both options in the code :
To use bot global update channel :
`
func start() {
	bot.AddHandler("/start", func(u *objs.Update) {
		// Sends the message to the chat that the message has been received from.
		// The message will be a reply to the received message.
		_, err := bot.SendMessage(u.Message.Chat.Id, "hi i'm a telegram bot", "", u.Message.MessageId, false, false)
		if err != nil {
			log.Fatal(err)
		}
	}, "private", "group") // this handler will only work if the received message is from a private chat or a group chat.
}

func main() {

	// update configs
	up := cfg.DefaultUpdateConfigs()

	// Bot configs
	cf := cfg.BotConfigs{
		BotAPI:         cfg.DefaultBotAPI,  //This is the address of the bot API server. If you are not running a local api server, use cfg.DefaultBotApi constant for this field.
		APIKey:         token,              // bot father api key
		UpdateConfigs:  up,                 // This is the update related configs such as update frequency (default : 300 milliseconds). You can use cfg.DefaultUpdateConfigs() method for this field
		Webhook:        false,              // Pass true if you want to use webhook for receiving updates. (Telego currently does not support webhook).
		LogFileAddress: cfg.DefaultLogFile, // the logs of the bot
	}

	bot, err = bt.NewBot(&cf)

	if err == nil {
		//Start the bot.
		err = bot.Run()
		if err == nil {
			start()
                        ch := bot.GetUpdateChannel()
                        for {
                                up := <- *ch
                       }
		} else {
			fmt.Println(err)
		}
	} else {
		fmt.Println(err)
	}
}
`

To use another channel :
`
func start() {
	bot.AddHandler("/start", func(u *objs.Update) {
		// Sends the message to the chat that the message has been received from.
		// The message will be a reply to the received message.
		_, err := bot.SendMessage(u.Message.Chat.Id, "hi i'm a telegram bot", "", u.Message.MessageId, false, false)
		if err != nil {
			log.Fatal(err)
		}
	}, "private", "group") // this handler will only work if the received message is from a private chat or a group chat.
}

func main() {

	// update configs
	up := cfg.DefaultUpdateConfigs()

	// Bot configs
	cf := cfg.BotConfigs{
		BotAPI:         cfg.DefaultBotAPI,  //This is the address of the bot API server. If you are not running a local api server, use cfg.DefaultBotApi constant for this field.
		APIKey:         token,              // bot father api key
		UpdateConfigs:  up,                 // This is the update related configs such as update frequency (default : 300 milliseconds). You can use cfg.DefaultUpdateConfigs() method for this field
		Webhook:        false,              // Pass true if you want to use webhook for receiving updates. (Telego currently does not support webhook).
		LogFileAddress: cfg.DefaultLogFile, // the logs of the bot
	}

	bot, err = bt.NewBot(&cf)
        ch := make(chan int)
	if err == nil {
		//Start the bot.
		err = bot.Run()
		if err == nil {
			start()
                        x <- ch
		} else {
			fmt.Println(err)
		}
	} else {
		fmt.Println(err)
	}
}
`
I hope it solves your issue :) 
We will try to fix this problem in the next release.

**Comment by ObiajuluM** [comment]
It works thanks.

By the next release this will be built into the `bot.Run()` method, right?

**Comment by SakoDroid** [comment]
I'm glad!
Exactly, we will work on it.
Thanks again for notifying us!
