### ISSUE TITLE
One Time keyboard

### ISSUE THREAD

**Issue by ZhangeldyB** [SakoDroid/telego#26]
in keyboardObjects.go 
there is an incorrect field: it has to be one_time_keyboard not one_tijme_keyboard (j is odd)
![image](https://github.com/SakoDroid/telego/assets/94115086/b7917bda-0493-413a-a85a-4b050d28457d)

**Comment by fulviodenza** [comment]
Hi @ZhangeldyB thanks for reporting this, do you want to open a PR?

**Comment by fulviodenza** [comment]
I've pushed a fix here: https://github.com/SakoDroid/telego/pull/25

**Comment by ZhangeldyB** [comment]
Ok, Thank you!
