### ISSUE TITLE
Always returns getWebhookInfo success...

### ISSUE THREAD

**Issue by jmoloko** [SakoDroid/telego#6]
**Hello!**
If I use code template from **"Quick start"**, I always get the same message in console - `getWebhookInfo success` and the bot finishes work.
What would that mean?
How to fix this situation?

**Comment by SakoDroid** [comment]
Hi, sorry for taking long to reply.
Another user had the same problem in this issue : https://github.com/SakoDroid/telego/issues/2
I hope it helps.
