### ISSUE TITLE
How to pin message

### ISSUE THREAD

**Issue by TommyLeng** [SakoDroid/telego#7]
https://core.telegram.org/bots/api#pinchatmessage

**Comment by SakoDroid** [comment]
Hi, to pin a message first you need to get a chat manager by one of the following methods : GetChatManagerByUsrename or GetChatManagerById.
After getting a chat manager you can use PinMessage an UnpinMessage mthods.

**Comment by TommyLeng** [comment]
Thanks a lot, it works. 

Just a little bit strange that 
I need to disable the Pin Message permission in the group first. 
And then enable the Pin message permission for my bot in administrator. 
Then I can pin message successfully.

Otherwise I will got error "not enough rights to manage pinned messages in the chat".
